In [1]:
import numpy as np
list1=[45,56,78,0,34]
myarray=np.array(list1)
print(myarray)
type(myarray)

[45 56 78  0 34]


numpy.ndarray

In [2]:
import numpy as np
list2=[[1,3,6],[6,4,8],[7,5,4]]
array1=np.array(list2)
print(array1)

[[1 3 6]
 [6 4 8]
 [7 5 4]]


In [6]:
import numpy as np
array1=np.arange(25,101,2)
print(array1)

[25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71
 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
import warnings
warnings.filterwarnings('ignore')
ip=pd.read_csv('C:/Users/Vilas/Downloads/mypython.csv')

In [9]:
ip.head()

Code                               Industry  \
0  A011100       Nursery Production (Under Cover)   
1  A011200          Nursery Production (Outdoors)   
2  A011300                           Turf Growing   
3  A011400  Floriculture Production (Under Cover)   
4  A011500     Floriculture Production (Outdoors)   

   Employed_census_usually_resident_population_count_aged_15_years_and_over  \
0                                               1191                          
1                                               1638                          
2                                                 66                          
3                                                834                          
4                                                132                          

   SalaryBonus  
0       5000.0  
1       1000.0  
2        500.0  
3        501.0  
4        502.0

In [10]:
ip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 513 entries, 0 to 512
Data columns (total 4 columns):
 #   Column                                                                    Non-Null Count  Dtype  
---  ------                                                                    --------------  -----  
 0   Code                                                                      513 non-null    object 
 1   Industry                                                                  513 non-null    object 
 2   Employed_census_usually_resident_population_count_aged_15_years_and_over  513 non-null    int64  
 3   SalaryBonus                                                               55 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 16.2+ KB


In [11]:
ip.columns

Index(['Code', 'Industry',
       'Employed_census_usually_resident_population_count_aged_15_years_and_over',
       'SalaryBonus'],
      dtype='object')

In [12]:
ip.count()

Code                                                                        513
Industry                                                                    513
Employed_census_usually_resident_population_count_aged_15_years_and_over    513
SalaryBonus                                                                  55
dtype: int64

In [13]:
import numpy as np
array1=np.arange(11,19).reshape((2,4))
print(array1)

[[11 12 13 14]
 [15 16 17 18]]
