# Numpy Basics Lab

Q.1)WAP to create array elements between 25 to 45(20 elements).Arrange them in equal size array.

In [1]:
import numpy as np

# Create an array with elements between 25 and 45
array = np.arange(25, 45)

# Ensure the array has exactly 20 elements
array = np.linspace(25, 45, 20, dtype=int)

# Print the original array
print("Original array:")
print(array)

# Split the array into equal-sized subarrays
equal_size_arrays = np.array_split(array, 2)

# Print the equally sized arrays
print("\nEqually sized arrays:")
for subarray in equal_size_arrays:
    print(subarray)

Original array:
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 45]

Equally sized arrays:
[25 26 27 28 29 30 31 32 33 34]
[35 36 37 38 39 40 41 42 43 45]


Q.2)Find array element greater than 10 

In [2]:
import numpy as np

# Create an example array
array = np.array([5, 12, 7, 18, 2, 25, 9, 11])

# Find elements greater than 10
greater_than_10 = array[array > 10]

# Print the result
print("Elements greater than 10:")
print(greater_than_10)

Elements greater than 10:
[12 18 25 11]


Q.3)WAP to concatenate two array apply all mathematical operator on the same

In [3]:
import numpy as np

# Create two arrays
array1 = np.array([56, 48, 79, 46, 76])
array2 = np.array([2, 4, 6, 8, 10])

# Concatenate the arrays
concatenated_array = np.concatenate((array1, array2))

# Print the concatenated array
print("Concatenated array:", concatenated_array)

# Apply mathematical operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 // array2

# Print the results
print("\nAddition:", addition)
print("\nSubtraction:", subtraction)
print("\nMultiplication:", multiplication)
print("\nDivision:", division)

Concatenated array: [56 48 79 46 76  2  4  6  8 10]

Addition: [58 52 85 54 86]

Subtraction: [54 44 73 38 66]

Multiplication: [112 192 474 368 760]

Division: [28 12 13  5  7]


Q.4) Extract all odd numbers from an array

In [4]:
import numpy as np

# Create an example array
array = np.array([5, 12, 7, 18, 2, 25, 9, 11])

# Extract odd numbers
odd_numbers = array[array % 2 != 0]

# Print the result
print("Odd numbers:", odd_numbers)

Odd numbers: [ 5  7 25  9 11]
